services:
  - type: web
    name: aptquiz-backend
    runtime: docker
    plan: free
    region: singapore
    dockerfilePath: ./Dockerfile
    autoDeployTrigger: commit
    envVars:
      - key: SPRING_DATASOURCE_URL
        sync: false
      - key: SPRING_DATASOURCE_USERNAME
        sync: false
      - key: SPRING_DATASOURCE_PASSWORD
        sync: false
      - key: SPRING_JPA_HIBERNATE_DDL_AUTO
        value: update
      - key: FRONTEND_URL
        sync: false
